<?php

namespace Arya;

interface Reason {

    const HTTP_100 = 'Continue',
          HTTP_101 = 'Switching Protocols',
          HTTP_200 = 'OK',
          HTTP_201 = 'Created',
          HTTP_202 = 'Accepted',
          HTTP_203 = 'Non-Authoritative Information',
          HTTP_204 = 'No Content',
          HTTP_205 = 'Reset Content',
          HTTP_206 = 'Partial Content',
          HTTP_300 = 'Multiple Choices',
          HTTP_301 = 'Moved Permanently',
          HTTP_302 = 'Found',
          HTTP_303 = 'See Other',
          HTTP_304 = 'Not Modified',
          HTTP_305 = 'Use Proxy',
          HTTP_307 = 'Temporary Redirect',
          HTTP_400 = 'Bad Request',
          HTTP_401 = 'Unauthorized',
          HTTP_402 = 'Payment Required',
          HTTP_403 = 'Forbidden',
          HTTP_404 = 'Not Found',
          HTTP_405 = 'Method Not Allowed',
          HTTP_406 = 'Not Acceptable',
          HTTP_407 = 'Proxy Authentication Required',
          HTTP_408 = 'Request Timeout',
          HTTP_409 = 'Conflict',
          HTTP_410 = 'Gone',
          HTTP_411 = 'Length Required',
          HTTP_412 = 'Precondition Failed',
          HTTP_413 = 'Request Entity Too Large',
          HTTP_414 = 'Request URI Too Long',
          HTTP_415 = 'Unsupported Media Type',
          HTTP_416 = 'Requested Range Not Satisfiable',
          HTTP_417 = 'Expectation Failed',
          HTTP_426 = 'Upgrade Required',
          HTTP_428 = 'Precondition Required',
          HTTP_429 = 'Too Many Requests',
          HTTP_431 = 'Request Header Fields Too Large',
          HTTP_500 = 'Internal Server Error',
          HTTP_501 = 'Not Implemented',
          HTTP_502 = 'Bad Gateway',
          HTTP_503 = 'Service Unavailable',
          HTTP_504 = 'Gateway Timeout',
          HTTP_505 = 'HTTP Version Not Supported',
          HTTP_511 = 'Network Authentication Required';

}
