<?php


namespace ImagickDemo;


interface Config {

    const IMAGICK_DEMOS_CACHE_IMAGES = 'IMAGICK_DEMOS_CACHE_IMAGES';
    const IMAGICK_DEMOS_QUEUE_IMAGES = 'IMAGICK_DEMOS_QUEUE_IMAGES';

    const IMAGICK_DEMOS_LIBRATO_KEY = 'IMAGICK_DEMOS_LIBRATO_KEY';
    const IMAGICK_DEMOS_LIBRATO_USERNAME = 'IMAGICK_DEMOS_LIBRATO_USERNAME';
    const IMAGICK_DEMOS_LIBRATO_STATS_SOURCE_NAME = 'IMAGICK_DEMOS_LIBRATO_STATS_SOURCE_NAME'; 
}

