<?php

$constants = [

//"STATISTIC_GRADIENT",
//"STATISTIC_MAXIMUM",
//"STATISTIC_MEAN",
//"STATISTIC_MEDIAN",
//"STATISTIC_MINIMUM",
//"STATISTIC_MODE",
//"STATISTIC_NONPEAK",
//"STATISTIC_STANDARD_DEVIATION",

"MORPHOLOGY_CONVOLVE",
"MORPHOLOGY_CORRELATE",

"MORPHOLOGY_ERODE",
"MORPHOLOGY_DILATE",
"MORPHOLOGY_ERODE_INTENSITY",
"MORPHOLOGY_DILATE_INTENSITY",
"MORPHOLOGY_DISTANCE",

"MORPHOLOGY_OPEN",
"MORPHOLOGY_CLOSE",
"MORPHOLOGY_OPEN_INTENSITY",
"MORPHOLOGY_CLOSE_INTENSITY",
"MORPHOLOGY_SMOOTH",

"MORPHOLOGY_EDGE_IN",
"MORPHOLOGY_EDGE_OUT",
"MORPHOLOGY_EDGE",
"MORPHOLOGY_TOP_HAT",
"MORPHOLOGY_BOTTOM_HAT",

"MORPHOLOGY_HIT_AND_MISS",
"MORPHOLOGY_THINNING",
"MORPHOLOGY_THICKEN",

"MORPHOLOGY_VORONOI",
"MORPHOLOGY_ITERATIVE",

"KERNEL_UNITY",
"KERNEL_GAUSSIAN",
"KERNEL_DIFFERENCE_OF_GAUSSIANS",
"KERNEL_LAPLACIAN_OF_GAUSSIANS",
"KERNEL_BLUR",
"KERNEL_COMET",

"KERNEL_LAPLACIAN",
"KERNEL_SOBEL",
"KERNEL_FREI_CHEN",
"KERNEL_ROBERTS",
"KERNEL_PREWITT",
"KERNEL_COMPASS",
"KERNEL_KIRSCH",

"KERNEL_DIAMOND",
"KERNEL_SQUARE",
"KERNEL_RECTANGLE",
"KERNEL_OCTAGON",
"KERNEL_DISK",
"KERNEL_PLUS",
"KERNEL_CROSS",
"KERNEL_RING",

"KERNEL_PEAKS",
"KERNEL_EDGES",
"KERNEL_CORNERS",
"KERNEL_DIAGONALS",
"KERNEL_LINE_ENDS",
"KERNEL_LINE_JUNCTIONS",
"KERNEL_RIDGES",
"KERNEL_CONVEX_HULL",
"KERNEL_THIN_SE",
"KERNEL_SKELETON",

"KERNEL_CHEBYSHEV",
"KERNEL_MANHATTAN",
"KERNEL_OCTAGONAL",
"KERNEL_EUCLIDEAN",

"KERNEL_USER_DEFINED",
"KERNEL_BINOMIAL",

"NORMALIZE_KERNEL_NONE",
"NORMALIZE_KERNEL_VALUE",
"NORMALIZE_KERNEL_CORRELATE",
"NORMALIZE_KERNEL_PERCENT",
"CHANNEL_RGBA"
    
    ];


foreach ($constants as $constant) {

    $reflection = new ReflectionClass('Imagick');

    $value = $reflection->getConstant($constant);
    
    //$value = \Imagick::${'constant'};
    //$value = constant("Imagick::$constant");
    
    echo "    const $constant = $value;\n";
    
}